# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 760)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(995, 760))
        MainWindow.setMaximumSize(QtCore.QSize(995, 760))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Watermelon_icn_cropped.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"    color: #9B9C9E;\n"
"}\n"
"\n"
"#MainWindow{\n"
"    background-color: #1A1D21;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #1A1D21;\n"
"}\n"
"#scrollAreaWidgetContents{\n"
"    background-color: #1A1D21;\n"
"}\n"
"#results{\n"
"    border: none;\n"
"}\n"
"#importButton{\n"
"    background-color: #0D0F10;\n"
"    color: #9B9C9E;\n"
"    border-radius: 12px;\n"
"    transition-duration: 0.4s;\n"
"}\n"
"#importButton:hover {\n"
"    cursor: pointer;\n"
"    background-color: #363A3D;\n"
"}\n"
"#importButton:disabled {\n"
"    background-color: #363A3D;\n"
"}\n"
"#startButton{\n"
"    background-color: #B6F09C;\n"
"    color: #0C1132;\n"
"    border-radius: 12px;\n"
"    transition-duration: 0.4s;\n"
"}\n"
"#startButton:hover {\n"
"    cursor: pointer;\n"
"    background-color: #C8F4B4;\n"
"}\n"
"#startButton:disabled {\n"
"    background-color: #739F5F;\n"
"}\n"
"#progressBar{\n"
"    background-color: #0D0F10;\n"
"    selection-background-color: #B6F09C;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setGeometry(QtCore.QRect(170, 520, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.importButton.setFont(font)
        self.importButton.setStyleSheet("")
        self.importButton.setObjectName("importButton")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(20, 20, 500, 361))
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setEnabled(False)
        self.startButton.setGeometry(QtCore.QRect(140, 590, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.results = QtWidgets.QScrollArea(self.centralwidget)
        self.results.setEnabled(True)
        self.results.setGeometry(QtCore.QRect(550, 20, 461, 681))
        self.results.setWidgetResizable(True)
        self.results.setObjectName("results")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 461, 681))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 16))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.results.setWidget(self.scrollAreaWidgetContents)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(190, 670, 171, 31))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 10)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Watermelon"))
        self.importButton.setText(_translate("MainWindow", "Импорт фото"))
        self.startButton.setText(_translate("MainWindow", "Начать"))
